#!/usr/bin/env php
<?php

use QApi\Enumeration\RunMode;

define('PROJECT_PATH',getcwd().DIRECTORY_SEPARATOR);
require 'vendor/autoload.php';
define('RUN_MODE', RunMode::DEVELOPMENT);
$Command = new \QApi\Command();
$Command->execute();